[package]
name = "docify_macros"
version = "0.1.0"
edition = "2021"
authors = ["sam0x17"]
license = "MIT"
description = "Support macros for docify"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-syn-parse = "0.1.5"
quote = "1"
syn = { version = "2", features = ["full"] }
