[package]
name = "docify_macros"
version = "0.1.0"
edition = "2021"
authors = ["sam0x17"]
license = "MIT"
description = "Support macros for docify"

[lib]
proc-macro = true

[dependencies]
derive-syn-parse = "0.1.5"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "visit"] }
